name: Publish Docker with build args
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: olegtarasov/get-tag@v2
        id: tagName
      - name: test env
        run: echo "tag is $GIT_TAG_NAME - dervied from $GITHUB_REF ::set-env name=VERSION::$GIT_TAG_NAME"
      - name: test alias env
        run: echo "alias is $VERSION"
