name: Publish Docker with build args
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: olegtarasov/get-tag@v2
        id: tagName
      - name: Alias GIT_TAG_NAME to VERSION
        run: echo "::set-env name=VERSION::$GIT_TAG_NAME"
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: onepanel/core-ui
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          snapshot: true
          buildargs: VERSION
          tag_semver: true
